
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrei
 */
public class LibrarianWindow extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianWindow
     */
   CardLayout cardLayout;
    public LibrarianWindow() {
        initComponents();
        
        
        cardLayout = (CardLayout)(panelCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        LibrarianWindowJLabel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        manageUsersButton = new javax.swing.JButton();
        manageBooksButton = new javax.swing.JButton();
        manageLoansButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        manageBooksPanelCard = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        addButtonManageBooks = new javax.swing.JButton();
        editButtonManageBooks = new javax.swing.JButton();
        deleteButtonManageBooks = new javax.swing.JButton();
        manageLoansPanelCard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        editButtonManageLoans = new javax.swing.JButton();
        addButtonManageLoans = new javax.swing.JButton();
        deleteButtonManageLoans = new javax.swing.JButton();
        manageUserPanelCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        editButtonManageUsers = new javax.swing.JButton();
        addButtonManageUsers = new javax.swing.JButton();
        deleteButtonManageUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1129, 593));

        LibrarianWindowJLabel.setBackground(new java.awt.Color(18, 203, 196));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Librarian Window");

        manageUsersButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageUsersButton.setForeground(new java.awt.Color(255, 255, 255));
        manageUsersButton.setText("Manage Users");
        manageUsersButton.setBorderPainted(false);
        manageUsersButton.setContentAreaFilled(false);
        manageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersButtonActionPerformed(evt);
            }
        });

        manageBooksButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageBooksButton.setForeground(new java.awt.Color(255, 255, 255));
        manageBooksButton.setText("Manage Books");
        manageBooksButton.setBorderPainted(false);
        manageBooksButton.setContentAreaFilled(false);
        manageBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBooksButtonActionPerformed(evt);
            }
        });

        manageLoansButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        manageLoansButton.setForeground(new java.awt.Color(255, 255, 255));
        manageLoansButton.setText("Manage Loans");
        manageLoansButton.setBorderPainted(false);
        manageLoansButton.setContentAreaFilled(false);
        manageLoansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLoansButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello, Librarian!");

        javax.swing.GroupLayout LibrarianWindowJLabelLayout = new javax.swing.GroupLayout(LibrarianWindowJLabel);
        LibrarianWindowJLabel.setLayout(LibrarianWindowJLabelLayout);
        LibrarianWindowJLabelLayout.setHorizontalGroup(
            LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibrarianWindowJLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibrarianWindowJLabelLayout.createSequentialGroup()
                            .addGroup(LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(manageLoansButton)
                                .addComponent(jLabel8))
                            .addGap(23, 23, 23))
                        .addGroup(LibrarianWindowJLabelLayout.createSequentialGroup()
                            .addGroup(LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(manageUsersButton)
                                .addComponent(manageBooksButton))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibrarianWindowJLabelLayout.createSequentialGroup()
                        .addGroup(LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        LibrarianWindowJLabelLayout.setVerticalGroup(
            LibrarianWindowJLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibrarianWindowJLabelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(56, 56, 56)
                .addComponent(manageUsersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageBooksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageLoansButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(logoutButton)
                .addGap(40, 40, 40))
        );

        jSplitPane2.setLeftComponent(LibrarianWindowJLabel);

        panelCards.setBackground(new java.awt.Color(196, 229, 56));
        panelCards.setLayout(new java.awt.CardLayout());

        manageBooksPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "ISBN", "Copy No.", "Author", "Year Published"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Books");

        addButtonManageBooks.setText("Add");
        addButtonManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonManageBooksActionPerformed(evt);
            }
        });

        editButtonManageBooks.setText("Edit");
        editButtonManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonManageBooksActionPerformed(evt);
            }
        });

        deleteButtonManageBooks.setText("Delete");
        deleteButtonManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonManageBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageBooksPanelCardLayout = new javax.swing.GroupLayout(manageBooksPanelCard);
        manageBooksPanelCard.setLayout(manageBooksPanelCardLayout);
        manageBooksPanelCardLayout.setHorizontalGroup(
            manageBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBooksPanelCardLayout.createSequentialGroup()
                .addGroup(manageBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageBooksPanelCardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButtonManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButtonManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButtonManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, manageBooksPanelCardLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(manageBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(manageBooksPanelCardLayout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jLabel3)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        manageBooksPanelCardLayout.setVerticalGroup(
            manageBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBooksPanelCardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButtonManageBooks)
                    .addComponent(editButtonManageBooks)
                    .addComponent(deleteButtonManageBooks))
                .addGap(51, 51, 51))
        );

        panelCards.add(manageBooksPanelCard, "manageBooksPanelCard");

        manageLoansPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("On Hold");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Title", "Author", "ISBN", "Transaction Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);

        editButtonManageLoans.setText("Edit");

        addButtonManageLoans.setText("Add");

        deleteButtonManageLoans.setText("Delete");

        javax.swing.GroupLayout manageLoansPanelCardLayout = new javax.swing.GroupLayout(manageLoansPanelCard);
        manageLoansPanelCard.setLayout(manageLoansPanelCardLayout);
        manageLoansPanelCardLayout.setHorizontalGroup(
            manageLoansPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLoansPanelCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageLoansPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLoansPanelCardLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageLoansPanelCardLayout.createSequentialGroup()
                        .addComponent(addButtonManageLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButtonManageLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButtonManageLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(manageLoansPanelCardLayout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        manageLoansPanelCardLayout.setVerticalGroup(
            manageLoansPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageLoansPanelCardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageLoansPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButtonManageLoans)
                    .addComponent(addButtonManageLoans)
                    .addComponent(editButtonManageLoans))
                .addGap(57, 57, 57))
        );

        panelCards.add(manageLoansPanelCard, "manageLoansPanelCard");

        manageUserPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Users");

        editButtonManageUsers.setText("Edit");
        editButtonManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonManageUsersActionPerformed(evt);
            }
        });

        addButtonManageUsers.setText("Add");
        addButtonManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonManageUsersActionPerformed(evt);
            }
        });

        deleteButtonManageUsers.setText("Delete");
        deleteButtonManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonManageUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageUserPanelCardLayout = new javax.swing.GroupLayout(manageUserPanelCard);
        manageUserPanelCard.setLayout(manageUserPanelCardLayout);
        manageUserPanelCardLayout.setHorizontalGroup(
            manageUserPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserPanelCardLayout.createSequentialGroup()
                .addGroup(manageUserPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(manageUserPanelCardLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButtonManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButtonManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButtonManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageUserPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(manageUserPanelCardLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(manageUserPanelCardLayout.createSequentialGroup()
                            .addGap(406, 406, 406)
                            .addComponent(jLabel2))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        manageUserPanelCardLayout.setVerticalGroup(
            manageUserPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUserPanelCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(manageUserPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButtonManageUsers)
                    .addComponent(editButtonManageUsers)
                    .addComponent(deleteButtonManageUsers))
                .addGap(58, 58, 58))
        );

        panelCards.add(manageUserPanelCard, "manageUserPanelCard");
        manageUserPanelCard.getAccessibleContext().setAccessibleParent(manageUserPanelCard);

        jSplitPane2.setRightComponent(panelCards);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersButtonActionPerformed
       cardLayout.show(panelCards,"manageUserPanelCard");
    }//GEN-LAST:event_manageUsersButtonActionPerformed

    private void manageBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBooksButtonActionPerformed
        cardLayout.show(panelCards,"manageBooksPanelCard");
    }//GEN-LAST:event_manageBooksButtonActionPerformed

    private void manageLoansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLoansButtonActionPerformed
        cardLayout.show(panelCards,"manageLoansPanelCard");
    }//GEN-LAST:event_manageLoansButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","Logging Out",JOptionPane.OK_OPTION);

        if(x==OK_OPTION){
            this.dispose();
        }else{
            return;
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void editButtonManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonManageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonManageUsersActionPerformed

    private void addButtonManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonManageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonManageUsersActionPerformed

    private void deleteButtonManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonManageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonManageUsersActionPerformed

    private void addButtonManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonManageBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonManageBooksActionPerformed

    private void editButtonManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonManageBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonManageBooksActionPerformed

    private void deleteButtonManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonManageBooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonManageBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LibrarianWindowJLabel;
    private javax.swing.JButton addButtonManageBooks;
    private javax.swing.JButton addButtonManageLoans;
    private javax.swing.JButton addButtonManageUsers;
    private javax.swing.JButton deleteButtonManageBooks;
    private javax.swing.JButton deleteButtonManageLoans;
    private javax.swing.JButton deleteButtonManageUsers;
    private javax.swing.JButton editButtonManageBooks;
    private javax.swing.JButton editButtonManageLoans;
    private javax.swing.JButton editButtonManageUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageBooksButton;
    private javax.swing.JPanel manageBooksPanelCard;
    private javax.swing.JButton manageLoansButton;
    private javax.swing.JPanel manageLoansPanelCard;
    private javax.swing.JPanel manageUserPanelCard;
    private javax.swing.JButton manageUsersButton;
    private javax.swing.JPanel panelCards;
    // End of variables declaration//GEN-END:variables
}
