CREATE SEQUENCE author_seq
    START WITH 0
    MINVALUE 0
    INCREMENT BY 1;
    
CREATE SEQUENCE USER_SEQ 
    START WITH 0
    INCREMENT BY 1 
    MINVALUE 0;

CREATE SEQUENCE book_transaction_seq
    START WITH 0
    INCREMENT BY 1 
    MINVALUE 0;
    
CREATE SEQUENCE book_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0;
    
CREATE SEQUENCE shelf_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0;