CREATE SEQUENCE author_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1;
    
CREATE SEQUENCE USER_SEQ 
    INCREMENT BY 1 
    START WITH 1
    MINVALUE 0;

CREATE SEQUENCE book_transaction_seq
    INCREMENT BY 1 
    START WITH 1
    MINVALUE 0;
    
CREATE SEQUENCE book_seq
    INCREMENT BY 1
    START WITH 1
    MINVALUE 0;
    
DROP sequence user_seq;