/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import customclass.LibUser;
import customclass.SearchBook;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import oracledb.SQLCore;

/**
 *
 * @author aevan
 */
public class EditBookDialog extends javax.swing.JDialog {
    private SearchBook book;
    /**
     * Creates new form EditBookDialog
     */
    public EditBookDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    public EditBookDialog(java.awt.Frame parent, boolean modal, SearchBook book){
        this(parent, modal);
        this.book = book;
        initFields();
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPane = new javax.swing.JPanel();
        contentPane = new javax.swing.JPanel();
        shelfLbl = new javax.swing.JLabel();
        shelfFld = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        isbnLbl = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        titleFld = new javax.swing.JTextField();
        yearFld = new javax.swing.JTextField();
        isbnFld = new javax.swing.JTextField();
        changeTitleBtn = new javax.swing.JButton();
        changeIsbnBtn = new javax.swing.JButton();
        changeYearBtn = new javax.swing.JButton();
        changeShelfBtn = new javax.swing.JButton();
        titlePane = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        editBookTitleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        registerPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setBackground(new java.awt.Color(196, 229, 56));

        shelfLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shelfLbl.setForeground(new java.awt.Color(255, 255, 255));
        shelfLbl.setText("Shelf No.");

        shelfFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shelfFld.setEnabled(false);

        regBtn.setBackground(new java.awt.Color(6, 82, 221));
        regBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regBtn.setForeground(new java.awt.Color(255, 255, 255));
        regBtn.setText("Apply");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(237, 76, 103));
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Title:");

        isbnLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnLbl.setForeground(new java.awt.Color(255, 255, 255));
        isbnLbl.setText("ISBN:");

        yearLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearLbl.setForeground(new java.awt.Color(255, 255, 255));
        yearLbl.setText("Year Published:");

        titleFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleFld.setEnabled(false);

        yearFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearFld.setEnabled(false);

        isbnFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnFld.setEnabled(false);

        changeTitleBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        changeTitleBtn.setText("Change");
        changeTitleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTitleBtnActionPerformed(evt);
            }
        });

        changeIsbnBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        changeIsbnBtn.setText("Change");
        changeIsbnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeIsbnBtnActionPerformed(evt);
            }
        });

        changeYearBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        changeYearBtn.setText("Change");
        changeYearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeYearBtnActionPerformed(evt);
            }
        });

        changeShelfBtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        changeShelfBtn.setText("Change");
        changeShelfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeShelfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shelfLbl)
                    .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(yearLbl))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(isbnLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(titleLbl, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(yearFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeYearBtn))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeTitleBtn))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeIsbnBtn))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regBtn))
                            .addComponent(shelfFld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeShelfBtn)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLbl))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(changeTitleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLbl)
                    .addComponent(isbnFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeIsbnBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeYearBtn)
                    .addComponent(yearLbl))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelfLbl)
                    .addComponent(shelfFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeShelfBtn))
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(227, 227, 227))
        );

        registerPane.add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 480, 300));

        titlePane.setBackground(new java.awt.Color(18, 203, 196));
        titlePane.setLayout(null);

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        titlePane.add(exitBtn);
        exitBtn.setBounds(427, 13, 25, 44);

        editBookTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editBookTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        editBookTitleLbl.setText("Edit Book");
        titlePane.add(editBookTitleLbl);
        editBookTitleLbl.setBounds(20, 10, 190, 44);

        registerPane.add(titlePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        try{
            if(emptyFields(shelfFld, titleFld, isbnFld, yearFld)){
                throw new Exception("Empty Fields!");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Some fields are empty",
                "Empty Fields",
                JOptionPane.ERROR_MESSAGE);

            return;
        }
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);

        if(x==JOptionPane.NO_OPTION){
            return;
        }
        String[] details = {isbnFld.getText(),
            titleFld.getText(),
            yearFld.getText(),
            shelfFld.getText()};
        
        SQLCore.editBook(book.getIsbn(), details);

        JOptionPane.showMessageDialog(this,
            "You have successfully edited the book",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);

        cancelBtn.doClick();
    }//GEN-LAST:event_regBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void changeTitleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTitleBtnActionPerformed
        titleFld.setEnabled(true);
    }//GEN-LAST:event_changeTitleBtnActionPerformed

    private void changeIsbnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeIsbnBtnActionPerformed
        isbnFld.setEnabled(true);
    }//GEN-LAST:event_changeIsbnBtnActionPerformed

    private void changeYearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeYearBtnActionPerformed
        yearFld.setEnabled(true);
    }//GEN-LAST:event_changeYearBtnActionPerformed

    private void changeShelfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeShelfBtnActionPerformed
        shelfFld.setEnabled(true);
    }//GEN-LAST:event_changeShelfBtnActionPerformed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        cancelBtn.doClick();
    }//GEN-LAST:event_exitBtnMouseClicked

    public boolean emptyFields(JTextField ... flds){
        for(JTextField item: flds){
            if(item.getText().isEmpty()){
                return true;
            }
        }
        
        return false;
    }
    
    private void initFields() {
        shelfFld.setText(Integer.toString(book.getShelfId()));
        titleFld.setText(book.getTitle());
        isbnFld.setText(book.getIsbn());
        yearFld.setText(Integer.toString(book.getYear()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBookDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditBookDialog dialog = new EditBookDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeIsbnBtn;
    private javax.swing.JButton changeShelfBtn;
    private javax.swing.JButton changeTitleBtn;
    private javax.swing.JButton changeYearBtn;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel editBookTitleLbl;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JTextField isbnFld;
    private javax.swing.JLabel isbnLbl;
    private javax.swing.JButton regBtn;
    private javax.swing.JPanel registerPane;
    private javax.swing.JTextField shelfFld;
    private javax.swing.JLabel shelfLbl;
    private javax.swing.JTextField titleFld;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePane;
    private javax.swing.JTextField yearFld;
    private javax.swing.JLabel yearLbl;
    // End of variables declaration//GEN-END:variables
}
