package gui;


import customclass.SearchBook;
import customclass.SearchBookView;
import customclass.LibUser;
import customclass.MyBook;
import customclass.MyBookView;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_OPTION;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import oracledb.SQLCore;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrei
 */
public class PatronFrame extends javax.swing.JFrame {
    private LibUser user;
    private SearchBookView searchBookList;
    private MyBookView myBookList;
    
    private DefaultTableModel searchBooksModel;
    private DefaultTableModel myBooksModel;
    /**
     * Creates new form PatronWindow
     */
    
    CardLayout cardLayout;
    public PatronFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        cardLayout = (CardLayout)(panelCards.getLayout());
    }
    
    public PatronFrame(LibUser user) {
        this();
        System.out.println("awit");
        System.out.println(user);
        this.user = user;
        initTableModels();
        fillTables();
        greetingLbl.setText("Hello, "+ this.user.fName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        registerPane = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        sidePane = new javax.swing.JPanel();
        myBooksBtn = new javax.swing.JButton();
        searchBooksBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        greetingLbl = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        myBooksPanelCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myBooksTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        searchBooksPanelCard = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchBooksTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        borrowBtn = new javax.swing.JButton();
        historyPanelCard = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Patron Window");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setUndecorated(true);

        sidePane.setBackground(new java.awt.Color(18, 203, 196));

        myBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        myBooksBtn.setForeground(new java.awt.Color(255, 255, 255));
        myBooksBtn.setText("My Books");
        myBooksBtn.setBorderPainted(false);
        myBooksBtn.setContentAreaFilled(false);
        myBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myBooksBtnActionPerformed(evt);
            }
        });

        searchBooksBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchBooksBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBooksBtn.setText("Search Books");
        searchBooksBtn.setBorderPainted(false);
        searchBooksBtn.setContentAreaFilled(false);
        searchBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBooksBtnActionPerformed(evt);
            }
        });

        aboutBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About");
        aboutBtn.setBorderPainted(false);
        aboutBtn.setContentAreaFilled(false);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        greetingLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        greetingLbl.setForeground(new java.awt.Color(255, 255, 255));
        greetingLbl.setText("Hello, User!");

        javax.swing.GroupLayout sidePaneLayout = new javax.swing.GroupLayout(sidePane);
        sidePane.setLayout(sidePaneLayout);
        sidePaneLayout.setHorizontalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidePaneLayout.createSequentialGroup()
                            .addGroup(sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(myBooksBtn)
                                .addComponent(searchBooksBtn)
                                .addComponent(aboutBtn))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePaneLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(greetingLbl)
                            .addGap(23, 23, 23)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePaneLayout.createSequentialGroup()
                        .addComponent(logoutBtn)
                        .addContainerGap())))
        );
        sidePaneLayout.setVerticalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(myBooksBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBooksBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(greetingLbl)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addGap(40, 40, 40))
        );

        jSplitPane2.setLeftComponent(sidePane);

        panelCards.setBackground(new java.awt.Color(196, 229, 56));
        panelCards.setLayout(new java.awt.CardLayout());

        myBooksPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        myBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Author", "ISBN", "Date Borrowed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myBooksTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(myBooksTable);
        if (myBooksTable.getColumnModel().getColumnCount() > 0) {
            myBooksTable.getColumnModel().getColumn(0).setResizable(false);
            myBooksTable.getColumnModel().getColumn(1).setResizable(false);
            myBooksTable.getColumnModel().getColumn(2).setResizable(false);
            myBooksTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("My Books");

        jButton11.setText("Return Book");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myBooksPanelCardLayout = new javax.swing.GroupLayout(myBooksPanelCard);
        myBooksPanelCard.setLayout(myBooksPanelCardLayout);
        myBooksPanelCardLayout.setHorizontalGroup(
            myBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myBooksPanelCardLayout.createSequentialGroup()
                .addGroup(myBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addGroup(myBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myBooksPanelCardLayout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(myBooksPanelCardLayout.createSequentialGroup()
                            .addGap(406, 406, 406)
                            .addComponent(jLabel2))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        myBooksPanelCardLayout.setVerticalGroup(
            myBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myBooksPanelCardLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addGap(17, 17, 17))
        );

        panelCards.add(myBooksPanelCard, "myBooksCard");

        searchBooksPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        searchBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title", "Author", "ISBN", "Available Copies", "Shelf No.", "IN", "OUT", "Reserved"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchBooksTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(searchBooksTable);
        if (searchBooksTable.getColumnModel().getColumnCount() > 0) {
            searchBooksTable.getColumnModel().getColumn(0).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(1).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(2).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(3).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(4).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(5).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(6).setResizable(false);
            searchBooksTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search Books");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Book Name:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        borrowBtn.setText("Borrow");
        borrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchBooksPanelCardLayout = new javax.swing.GroupLayout(searchBooksPanelCard);
        searchBooksPanelCard.setLayout(searchBooksPanelCardLayout);
        searchBooksPanelCardLayout.setHorizontalGroup(
            searchBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBooksPanelCardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(searchBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borrowBtn)
                    .addGroup(searchBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(searchBooksPanelCardLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jButton6)
                            .addGap(18, 18, 18)
                            .addComponent(jButton7))
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        searchBooksPanelCardLayout.setVerticalGroup(
            searchBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBooksPanelCardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(searchBooksPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrowBtn)
                .addGap(19, 19, 19))
        );

        panelCards.add(searchBooksPanelCard, "searchBooksCard");

        historyPanelCard.setBackground(new java.awt.Color(196, 229, 56));

        javax.swing.GroupLayout historyPanelCardLayout = new javax.swing.GroupLayout(historyPanelCard);
        historyPanelCard.setLayout(historyPanelCardLayout);
        historyPanelCardLayout.setHorizontalGroup(
            historyPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyPanelCardLayout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401))
        );
        historyPanelCardLayout.setVerticalGroup(
            historyPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelCardLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        panelCards.add(historyPanelCard, "historyCard");

        jSplitPane2.setRightComponent(panelCards);

        javax.swing.GroupLayout registerPaneLayout = new javax.swing.GroupLayout(registerPane);
        registerPane.setLayout(registerPaneLayout);
        registerPaneLayout.setHorizontalGroup(
            registerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        registerPaneLayout.setVerticalGroup(
            registerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myBooksBtnActionPerformed
       cardLayout.show(panelCards,"myBooksCard");
    }//GEN-LAST:event_myBooksBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        cardLayout.show(panelCards,"historyCard");
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void searchBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBooksBtnActionPerformed
        cardLayout.show(panelCards,"searchBooksCard");
    }//GEN-LAST:event_searchBooksBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","Logging Out",JOptionPane.OK_OPTION);

        if(x==OK_OPTION){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }else{
            return;
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      jTextField1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void borrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBtnActionPerformed
        SearchBook selectedBook = searchBookList.getBook(searchBooksTable.getSelectedRow());
        
        int choice = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to borrow this book?",
                "Confirm", 
                JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            SQLCore.borrowBook(user, selectedBook);
            JOptionPane.showMessageDialog(this, 
                    "You have successfully borrowed " + selectedBook.getTitle(), 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_borrowBtnActionPerformed
    
    public void initTableModels(){
        
        searchBooksModel = new BookTableModel();
        searchBooksModel.setColumnIdentifiers(new String[] {"Title","Author","ISBN","Copies","Shelf No.","On Shelf","On Loan","On Hold"});
        searchBooksTable.setModel(searchBooksModel);
        
        myBooksModel = new BookTableModel();
        myBooksModel.setColumnIdentifiers(new String[] {"Title","Author","ISBN","Copy No.","Transaction Date", "Status"});
        myBooksTable.setModel(myBooksModel);
        
    }
    
    public void fillTables(){
        searchBookList = new SearchBookView();
        searchBookList.fill();
        
        ArrayList<SearchBook> searchList = searchBookList.getBookList();
        
        for(SearchBook item: searchList){
            searchBooksModel.addRow(item.toRow());
        }
        System.out.println(user.userId);
        myBookList = new MyBookView(user.userId);
        myBookList.fill();
        ArrayList<MyBook> myList = myBookList.getBookList();
        
        for(MyBook item: myList){
            myBooksModel.addRow(item.toRow());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatronFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatronFrame().setVisible(true);
            }
        });
    }
    
    public class BookTableModel extends DefaultTableModel{
        @Override
        public boolean isCellEditable(int rowIndex, int mColIndex){
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton borrowBtn;
    private javax.swing.JLabel greetingLbl;
    private javax.swing.JPanel historyPanelCard;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton myBooksBtn;
    private javax.swing.JPanel myBooksPanelCard;
    private javax.swing.JTable myBooksTable;
    private javax.swing.JPanel panelCards;
    private javax.swing.JPanel registerPane;
    private javax.swing.JButton searchBooksBtn;
    private javax.swing.JPanel searchBooksPanelCard;
    private javax.swing.JTable searchBooksTable;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
