--------------------------------------------------------
--  File created - Thursday-March-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHORS
--------------------------------------------------------

  CREATE TABLE "DBMS2"."AUTHORS" 
   (	"AUTHOR_ID" NUMBER(6,0), 
	"AUTHOR_NAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBMS2.AUTHORS
SET DEFINE OFF;
Insert into DBMS2.AUTHORS (AUTHOR_ID,AUTHOR_NAME) values (1,'Aevan Candelaria');
Insert into DBMS2.AUTHORS (AUTHOR_ID,AUTHOR_NAME) values (2,'Herman Cowell');
Insert into DBMS2.AUTHORS (AUTHOR_ID,AUTHOR_NAME) values (3,'Steven Stranger');
Insert into DBMS2.AUTHORS (AUTHOR_ID,AUTHOR_NAME) values (4,'Fernad Corbin');
--------------------------------------------------------
--  DDL for Index AUTHOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBMS2"."AUTHOR_PK" ON "DBMS2"."AUTHORS" ("AUTHOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AUTHORS
--------------------------------------------------------

  ALTER TABLE "DBMS2"."AUTHORS" ADD CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBMS2"."AUTHORS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."AUTHORS" MODIFY ("AUTHOR_NAME" NOT NULL ENABLE);
