--------------------------------------------------------
--  File created - Thursday-March-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKS
--------------------------------------------------------

  CREATE TABLE "DBMS2"."BOOKS" 
   (	"ISBN" VARCHAR2(15 BYTE), 
	"COPY_NO" NUMBER, 
	"TITLE" VARCHAR2(64 BYTE), 
	"YEAR_PUBLISHED" VARCHAR2(4 BYTE), 
	"STATUS" VARCHAR2(128 BYTE), 
	"SHELF_ID" NUMBER(6,0), 
	"BOOK_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBMS2.BOOKS
SET DEFINE OFF;
Insert into DBMS2.BOOKS (ISBN,COPY_NO,TITLE,YEAR_PUBLISHED,STATUS,SHELF_ID,BOOK_ID) values ('1234567',1,'To Kill A Bird','1999','On Loan',1,4);
Insert into DBMS2.BOOKS (ISBN,COPY_NO,TITLE,YEAR_PUBLISHED,STATUS,SHELF_ID,BOOK_ID) values ('0000001',1,'Alawanatics 101','2020','On Loan',1,1);
Insert into DBMS2.BOOKS (ISBN,COPY_NO,TITLE,YEAR_PUBLISHED,STATUS,SHELF_ID,BOOK_ID) values ('0000002',1,'Dormammu Bargains','2017','On Shelf',1,3);
Insert into DBMS2.BOOKS (ISBN,COPY_NO,TITLE,YEAR_PUBLISHED,STATUS,SHELF_ID,BOOK_ID) values ('0000002',2,'Dormammu Bargains','2017','On Shelf',1,2);
--------------------------------------------------------
--  DDL for Index BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBMS2"."BOOK_PK" ON "DBMS2"."BOOKS" ("BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "DBMS2"."BOOKS" ADD CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBMS2"."BOOKS" MODIFY ("ISBN" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."BOOKS" MODIFY ("COPY_NO" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."BOOKS" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."BOOKS" MODIFY ("YEAR_PUBLISHED" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."BOOKS" MODIFY ("SHELF_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKS
--------------------------------------------------------

  ALTER TABLE "DBMS2"."BOOKS" ADD CONSTRAINT "BOOK_SHELF_FK" FOREIGN KEY ("SHELF_ID")
	  REFERENCES "DBMS2"."SHELVES" ("SHELF_ID") ENABLE;
