--------------------------------------------------------
--  File created - Thursday-March-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SHELVES
--------------------------------------------------------

  CREATE TABLE "DBMS2"."SHELVES" 
   (	"SHELF_ID" NUMBER(6,0), 
	"CAPACITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBMS2.SHELVES
SET DEFINE OFF;
Insert into DBMS2.SHELVES (SHELF_ID,CAPACITY) values (1,100);
Insert into DBMS2.SHELVES (SHELF_ID,CAPACITY) values (2,100);
Insert into DBMS2.SHELVES (SHELF_ID,CAPACITY) values (3,100);
Insert into DBMS2.SHELVES (SHELF_ID,CAPACITY) values (4,100);
Insert into DBMS2.SHELVES (SHELF_ID,CAPACITY) values (5,100);
--------------------------------------------------------
--  DDL for Index SHELF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBMS2"."SHELF_PK" ON "DBMS2"."SHELVES" ("SHELF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SHELVES
--------------------------------------------------------

  ALTER TABLE "DBMS2"."SHELVES" ADD CONSTRAINT "SHELF_PK" PRIMARY KEY ("SHELF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBMS2"."SHELVES" MODIFY ("SHELF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."SHELVES" MODIFY ("CAPACITY" NOT NULL ENABLE);
