--------------------------------------------------------
--  File created - Thursday-March-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LIBRARY_USERS
--------------------------------------------------------

  CREATE TABLE "DBMS2"."LIBRARY_USERS" 
   (	"USER_ID" NUMBER(6,0), 
	"LOGIN_ID" VARCHAR2(32 BYTE), 
	"FIRST_NAME" VARCHAR2(64 BYTE), 
	"LAST_NAME" VARCHAR2(64 BYTE), 
	"LOGIN_PASSWORD" VARCHAR2(128 BYTE), 
	"ADDRESS" VARCHAR2(128 BYTE), 
	"LIBRARIAN" CHAR(1 BYTE), 
	"UNPAID_FINES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBMS2.LIBRARY_USERS
SET DEFINE OFF;
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (3,'bob','Robert','California','890','Las Vegas, Nevada','Y',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (25,'orhtej','Ed Jethro','Pacaño','edjethro','Bulacan','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (1,'aevan','Aevan','Candelaria','samgyup','Sampaloc, Manila','Y',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (2,'andrei','Andrei','Ofrecio','123','Tarlac, Tarlac','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (5,'dtam','Daniel','Tam','boris','Bicol','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (23,'johndenver','John','Denver','rockymountainhigh','West Virginia','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (41,'trexone','Rex','Ronquillo','123','Puso mo','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (42,'rovic','Rovic','Tabucol','hello','Manila','N',0);
Insert into DBMS2.LIBRARY_USERS (USER_ID,LOGIN_ID,FIRST_NAME,LAST_NAME,LOGIN_PASSWORD,ADDRESS,LIBRARIAN,UNPAID_FINES) values (43,'rovic','Rovic','Tabucol','hello','Manila','N',0);
--------------------------------------------------------
--  DDL for Index LIBRARY_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBMS2"."LIBRARY_USER_PK" ON "DBMS2"."LIBRARY_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LIBRARY_USERS
--------------------------------------------------------

  ALTER TABLE "DBMS2"."LIBRARY_USERS" ADD CONSTRAINT "CHECK_LIBRARIAN" CHECK ( librarian = 'Y' OR librarian = 'N' ) ENABLE;
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" ADD CONSTRAINT "LIBRARY_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("LOGIN_PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "DBMS2"."LIBRARY_USERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
